### ISSUE TITLE
error installing anchorecli on debian 10

### ISSUE THREAD

**Issue by khanattlab** [anchore/anchore-cli#182]
pip install anchorecli
Collecting anchorecli
  Using cached https://files.pythonhosted.org/packages/bb/d3/3ab8259d275ed39d98bb83d6d718c81c1695588959618dbdda5ff583350a/anchorecli-0.9.3.tar.gz
Collecting Click==8.0.1 (from anchorecli)
  Could not find a version that satisfies the requirement Click==8.0.1 (from anchorecli) (from versions: 0.1, 0.2, 0.3, 0.4, 0.5, 0.5.1, 0.6, 0.7, 1.0, 1.1, 2.0, 2.1, 2.2, 2.3, 2.4, 2.5, 2.6, 3.0, 3.1, 3.2, 3.3, 4.0, 4.1, 5.0, 5.1, 6.0, 6.1, 6.2, 6.3, 6.4, 6.5, 6.6, 6.7.dev0, 6.7, 7.0, 7.1, 7.1.1, 7.1.2)
No matching distribution found for Click==8.0.1 (from anchorecli)

**Comment by subecho** [comment]
Hey @khanattlab! It looks like the version of `Click` that `anchorecli` is looking for is only available for [Python versions >= 3.6](https://pypi.org/project/click/8.0.1/). You might want to try running that again with `pip3 install anchorecli` to ensure that you're using the Python 3 version of `pip` instead of Python 2 (which is probably the default on Debian 10.)

**Comment by khanattlab** [comment]
Figured it out and got it working. Thanks
