### ISSUE TITLE
Unable to delete or update existing registry (Error: unhashable type: 'list')

### ISSUE THREAD

**Issue by henrikjohansen** [anchore/anchore-cli#30]
Using anchore/engine-cli:latest : 

```
$ anchore-cli registry list
Registry                                                       Type             User
registry.gitlab.com/xxxxx/xxxx-management/xxxx-xxx        docker_v2        gitlab-ci-token
```

Delete fails :
```
$ anchore-cli registry del registry.gitlab.com/xxxxx/xxxx-management/xxxx-xxx
Error: unhashable type: 'list'
```

Update fails : 
```
$anchore-cli registry update registry.gitlab.com/xxxxx/xxxx-management/xxxx-xxx user pass
Error: unhashable type: 'list'
```

**Comment by nurmi** [comment]
hi @henrikjohansen 

There is a bug v0.3.4 when running anchore-cli with python2 that manifests in this fashion - we do have a fix committed which will be in the next release of the CLI (commit f5b0bcc35ebc9e659c80066721205e435ec0341c)

As an intermediate solution, can you use the CLI by calling the engine-cli container?  Specifically, the v0.3-dev tag has the fix included:

```
# docker run -t -i docker.io/anchore/engine-cli:v0.3-dev anchore-cli --url http://<your-anchore-engine-host>:8228/v1 registry get docker.io
Registry: docker.io
User: *****
Type: docker_v2
Verify TLS: True
Created: 2019-04-11T23:01:41Z
Updated: 2019-04-11T23:01:41Z
```

The fix is in both the latest 'master' as well as the '0.3' series code branches.

**Comment by henrikjohansen** [comment]
hi @nurmi 

Thanks a lot, ☝️ fixes that issue. I'll run with `engine-cli:v0.3-dev` until the next release is out :)
