### ISSUE TITLE
Repo watching subscribes to all tagged images, ignoring --lookuptag and --noautosubscribe

### ISSUE THREAD

**Issue by owms** [anchore/anchore-cli#8]
The repo watching functionality is not well documented yet so I'm not sure if this is a bug or intended behavior but I'm strongly leaning towards bug.  When I add a repo for scanning and specify a `--lookuptag`, anchore still attempts to pull and analyze all images from that repo, even the ones that do not match the tag.  It also creates analysis_update subscriptions even is using `--noautosubscribe`.

Ex. `anchore-cli repo add docker.io/library/httpd --noautosubscribe --lookuptag alpine`
after a few minutes we see all of the tags for that image were brought in for analyzing, not just :alpine 
```$ anchore-cli image list
Full Tag                                                                              Image ID                                                                Analysis Status        
docker.io/library/httpd:2                                                             01154c38b473722ac5b2bf19bc7d8a48d1a742fb02682efa583319126973b1c3        analysis_failed        
docker.io/library/httpd:2-alpine                                                      eac2f92ecb09947fa430a38c5eeb6a28d9d3b21958ecbed69013fb189484b2b1        analysis_failed        
docker.io/library/httpd:2.2                                                           e06c3dbbfe239c6fca50b6ab6935b3122930fa2eea2136979e5b46ad77ecb685        analysis_failed        
docker.io/library/httpd:2.2-alpine                                                    32dbd9b9dc151ff61b604c5924fa0e251678fba90136a3d4e24ba06364e52ab1        analysis_failed        
docker.io/library/httpd:2.2.29                                                        0a39699d267aaee04382c6b1b4fe2fc30737450fe8d4fabd88eee1a3e0016144        analysis_failed        
docker.io/library/httpd:2.2.31                                                        c8a7fb36e3abfc42f15f2a2a9293f1768a5b568fd7ac51546f0055e399c29aef        analysis_failed        
docker.io/library/httpd:2.2.31-alpine                                                 53ecdc16a2ecff5b3917ef84af6c889cb3f1c0a6066378cb92e3e81e85f9f481        analysis_failed        
docker.io/library/httpd:2.2.32                                                        c51e86ea30d138a7fd385c238aa63063b5f5d1d5f402ee99e4b06f21e28d3b0e        analysis_failed        
docker.io/library/httpd:2.2.32-alpine                                                 7a2ba448912337880d17878c1d7dd18b42e1230c2d391c58d85e40e3a4fb23e0        analysis_failed        
docker.io/library/httpd:2.2.34                                                        e06c3dbbfe239c6fca50b6ab6935b3122930fa2eea2136979e5b46ad77ecb685        analysis_failed        
docker.io/library/httpd:2.2.34-alpine                                                 32dbd9b9dc151ff61b604c5924fa0e251678fba90136a3d4e24ba06364e52ab1        analysis_failed        
docker.io/library/httpd:2.4                                                           01154c38b473722ac5b2bf19bc7d8a48d1a742fb02682efa583319126973b1c3        analysis_failed         
...  
```

Similar situation with the subscriptions that --noautosubscribe (I think?) should prevent subscriptions from being created for these images:
```$ anchore-cli subscription list
Tag                                                                                   Subscription Type        Active              
docker.io/library/httpd                                                               repo_update              True          
docker.io/library/httpd:2                                                             analysis_update          True          
docker.io/library/httpd:2                                                             policy_eval              False         
docker.io/library/httpd:2                                                             tag_update               False         
docker.io/library/httpd:2                                                             vuln_update              False         
docker.io/library/httpd:2-alpine                                                      analysis_update          True          
docker.io/library/httpd:2-alpine                                                      policy_eval              False         
docker.io/library/httpd:2-alpine                                                      tag_update               False         
docker.io/library/httpd:2-alpine                                                      vuln_update              False         
docker.io/library/httpd:2.2                                                           analysis_update          True          
docker.io/library/httpd:2.2                                                           policy_eval              False         
docker.io/library/httpd:2.2                                                           tag_update               False         
docker.io/library/httpd:2.2                                                           vuln_update              False 
...
```
I did a pull and build on both the CLI and Engine today so these commands were run using version 0.19dev 

Repo watching looks like a very useful feature.  It would be most useful to us if we can scan just the latest image in a repo, instead of all tagged images which seems to be the current behavior.

**Comment by nurmi** [comment]
hi @owms 

Glad you're taking a look at that new feature!  First we should clairify what those options mean (we hear you on better docs for new features - and will be on it!)

noautosubscribe: the first time a repo is added (anchore-cli repo add <blah>), the --noautosubscribe will set a flag on the repo that should prevent the engine from automatically enabling the tag_update  subscription, for new images that are found, when the repo scan comes around to add newly discovered image tags from the added repo.  From the output, it does look like that behavior is what you're seeing (the tag_update subscriptions are set to False for images added by the repo scan).  the analysis_update subscription is currently always enabled by default (it just controls whether the webhook notification is fired for those tags, if webhooks are set up).

lookuptag: this is an odd one - by default, the repo scanning implementation *requires* knowledge of at least one present tag in the repo, in order to be able to obtain the list of tags in the repo.  If lookuptag is not specified, then the implementation assumes ':latest' in order to fetch the full tag list.  This option is only needed when we want to add a repo for scanning that does not contain a ':latest' tag, allowing us to specify a tag the does exist so that the tag list can be obtained.  Currently, there is not a function to allow only a subset of tags to be watched by the repo scan, it is an all or nothing.

However, if you really are only interested in watching the ':latest' tag for repos, then you can always use the regular image add, plus tag_update subscription capability of anchore-engine.  

```
anchore-cli image add blah:latest
```

by default, the above will enable the 'tag_update' subscription, which means that the anchore-engine will periodically query the registry for updates to blah:latest and pull the image in (and analyze it) if a new digest is discovered that has that tag.  You can do this for any tag (not just :latest) using a regular image add (and be sure the tag_update subscription is active for any tag you want the system to watch automatically).

Does this clarify the functionality a bit better?  We'll make sure to work on better docs especially around new features like repo scan!

Best
-Dan

**Comment by owms** [comment]
Thanks for the explanation, that helped.  Closing issue since it is expected behavior.
